### ISSUE TITLE
Clarify (remove?) documentation related to pantheon.upstream.yml

### ISSUE THREAD

**Issue by markfullmer** [pantheon-systems/drupal-integrations#3]
The documentation for this project includes a section on disabling the scaffolding for `pantheon.upstream.yml` at https://github.com/pantheon-systems/drupal-integrations#special-instructions-for-upstreams

However, commit https://github.com/pantheon-systems/drupal-integrations/commit/ba2317c62d4efe84d539b7dcc965d8c389e7530f removed the `pantheon.upstream.yml` from this package.

Assuming the intent is that this package is not responsible for scaffolding the `pantheon.upstream.yml` (or, per https://github.com/pantheon-systems/drupal-integrations/commit/7649ccfa0f26503ba250d94fd4c146f0feb1d2d3, the `pantheon.yml`), the documentation referenced above can be removed.

**Comment by greg-1-anderson** [comment]
Fixed by https://github.com/pantheon-systems/drupal-integrations/commit/b452b9767cbd6f2aa1991ed855556169c68dba07. Thanks.
